//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCCSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Center
    {
        public string CenterName { get; set; }
        public string InstitutionName { get; set; }
        public int GrantNumber { get; set; }
        public string MigrationSource { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string Comments { get; set; }
        public string LastUpdatedUserName { get; set; }
        public string StreetAddress { get; set; }
        public string City { get; set; }
        public string StateCode { get; set; }
        public int CenterId { get; set; }
        public string ZipCode { get; set; }
        public string StreetAddress2 { get; set; }
        public Nullable<int> CenterTypeID { get; set; }
        public string ProfileURL { get; set; }
        public string CompeteCycle { get; set; }
        public Nullable<int> DesignationYear { get; set; }
        public Nullable<int> ComprehensivenessYear { get; set; }
    }
}
