//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCCSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CenterDetail
    {
        public Nullable<double> P30Type { get; set; }
        public string P30GrantNumber { get; set; }
        public string PIName { get; set; }
        public string PD { get; set; }
        public string C2014BudgetStart { get; set; }
        public string C2014BudgetEnd { get; set; }
        public Nullable<System.DateTime> C2015BudgetStart { get; set; }
        public Nullable<System.DateTime> eDataDueDate { get; set; }
        public Nullable<int> GrantNumber { get; set; }
        public int CenterDetailID { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<int> CenterID { get; set; }
        public Nullable<int> FY { get; set; }
        public Nullable<int> PDPersonID { get; set; }
        public string InstitutionName { get; set; }
    
        public virtual Center Center { get; set; }
    }
}
