//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCCSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCCList
    {
        public string CenterType { get; set; }
        public string profileURL { get; set; }
        public string InstitutionName { get; set; }
        public string CenterName { get; set; }
        public string FullName { get; set; }
        public string PIDegree { get; set; }
        public string PITitle { get; set; }
        public string StateCode { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public int CenterId { get; set; }
    }
}
