//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCCSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCOE
    {
        public int COEID { get; set; }
        public Nullable<int> fy { get; set; }
        public string CenterType { get; set; }
        public string InstitutionName { get; set; }
        public string FullName { get; set; }
        public string Titles { get; set; }
        public string Emails { get; set; }
    }
}
