//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCCSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwDT1cMember
    {
        public int dt1cFY { get; set; }
        public Nullable<int> dt1cGrantNumber { get; set; }
        public string dt1cInstitutionName { get; set; }
        public Nullable<int> AlignedNumber { get; set; }
        public Nullable<int> NonAlignedNumber { get; set; }
    }
}
