//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCCSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwDView
    {
        public int GrantNumber { get; set; }
        public string InstitutionName { get; set; }
        public int CenterId { get; set; }
        public Nullable<double> FY { get; set; }
        public string P30Partner { get; set; }
        public string FullProjNo { get; set; }
        public string ProjTitle { get; set; }
        public Nullable<System.DateTime> BudgetStartDate { get; set; }
        public Nullable<System.DateTime> BudgetEndDate { get; set; }
        public string PIname { get; set; }
        public Nullable<double> TotalCost { get; set; }
        public Nullable<int> NCITotalNo { get; set; }
        public Nullable<int> NCIDC { get; set; }
        public Nullable<int> NCITC { get; set; }
        public Nullable<int> OthNIHTotalNo { get; set; }
        public Nullable<int> OthNIHDC { get; set; }
        public Nullable<int> OthNIHTC { get; set; }
        public Nullable<int> OthPRTotalNo { get; set; }
        public Nullable<int> OthPRDC { get; set; }
        public Nullable<int> OthPRTC { get; set; }
        public Nullable<int> IndNonPRTotalNo { get; set; }
        public Nullable<int> IndNonPRDC { get; set; }
        public Nullable<int> IndNonPRTC { get; set; }
        public Nullable<int> OthNonPRTotalNo { get; set; }
        public Nullable<int> OthNonPRDC { get; set; }
        public Nullable<int> OthNonPRTC { get; set; }
        public Nullable<int> AlignedNumber { get; set; }
        public Nullable<int> NonAlignedNumber { get; set; }
    }
}
