//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCCSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwICD
    {
        public int ICDCodeID { get; set; }
        public Nullable<int> index { get; set; }
        public string PrimarySite { get; set; }
        public string icd { get; set; }
        public string icdo3 { get; set; }
    }
}
