//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCCSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwRP
    {
        public string CenterType { get; set; }
        public string InstitutionName { get; set; }
        public string CenterName { get; set; }
        public string ProgName { get; set; }
        public int DT1BProgramID { get; set; }
        public Nullable<int> fy { get; set; }
        public string FullNname { get; set; }
    }
}
